export const catsData = [
  {
    emotionTags: ["moody"],
    isGif: false,
    image: "angry.webp",
    alt: "A cat looking moody",
  },
  {
    emotionTags: ["moody", "insomniac"],
    isGif: false,
    image: "angry2.webp",
    alt: "A cat looking moody",
  },
  {
    emotionTags: ["moody"],
    isGif: false,
    image: "angry3.webp",
    alt: "A cat looking moody",
  },
  {
    emotionTags: ["confused", "sad"],
    isGif: false,
    image: "confused.webp",
    alt: "A cat looking confused",
  },
  {
    emotionTags: ["dominant", "moody"],
    isGif: false,
    image: "dominant.webp",
    alt: "A cat looking dominant",
  },
  {
    emotionTags: ["happy", "relaxed"],
    isGif: false,
    image: "happy.webp",
    alt: "A cat looking happy",
  },
  {
    emotionTags: ["hungry"],
    isGif: false,
    image: "hungry.webp",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["hungry"],
    isGif: false,
    image: "hungry1.webp",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["insomniac"],
    isGif: false,
    image: "insomnia.webp",
    alt: "A cat looking insomniac",
  },
  {
    emotionTags: ["insomniac"],
    isGif: false,
    image: "insomnia1.webp",
    alt: "A cat looking insomniac",
  },
  {
    emotionTags: ["relaxed"],
    isGif: false,
    image: "lazy.webp",
    alt: "A cat looking lazy",
  },
  {
    emotionTags: ["scared"],
    isGif: false,
    image: "nervous.webp",
    alt: "A cat looking nervous",
  },
  {
    emotionTags: ["sad"],
    isGif: false,
    image: "sad.webp",
    alt: "A cat looking sad",
  },
  {
    emotionTags: ["sad", "moody"],
    isGif: false,
    image: "sad1.webp",
    alt: "A cat looking sad",
  },
  {
    emotionTags: ["moody"],
    isGif: true,
    image: "angry.webp",
    alt: "A cat looking moody",
  },
  {
    emotionTags: ["moody"],
    isGif: true,
    image: "angry2.webp",
    alt: "A cat looking angry",
  },
  {
    emotionTags: ["confused"],
    isGif: true,
    image: "confused2.webp",
    alt: "A cat looking confused",
  },
  {
    emotionTags: ["dominant"],
    isGif: true,
    image: "dominant.webp",
    alt: "A cat looking dominant",
  },
  {
    emotionTags: ["happy"],
    isGif: true,
    image: "happy.webp",
    alt: "A cat looking happy",
  },
  {
    emotionTags: ["hungry", "sad", "confused"],
    isGif: true,
    image: "confused.webp",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["hungry"],
    isGif: true,
    image: "hungry.webp",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["hungry"],
    isGif: true,
    image: "hungry2.webp",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["insomniac", "scared"],
    isGif: true,
    image: "insomnia2.webp",
    alt: "A cat looking insomniac",
  },
  {
    emotionTags: ["relaxed"],
    isGif: true,
    image: "lazy.webp",
    alt: "A cat looking relaxed",
  },
  {
    emotionTags: ["relaxed"],
    isGif: true,
    image: "relaxed2.webp",
    alt: "A cat looking relaxed",
  },
  {
    emotionTags: ["scared", "sad"],
    isGif: true,
    image: "nervous.webp",
    alt: "A cat looking nervous",
  },
  {
    emotionTags: ["scared"],
    isGif: true,
    image: "nervous2.webp",
    alt: "A cat looking scared",
  },
  {
    emotionTags: ["sad"],
    isGif: true,
    image: "sad.webp",
    alt: "A cat looking sad",
  },
];
